version:  '3.8'
services:
  # MySQL
  db-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=user_name
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  # PGSql
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_DB: your_database_name
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # MongoDB
  db-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
volumes:
  db:
    driver: local